# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julie Eckstrom
email: julie.eckstrom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Julie Eckstrom is a designer in Pittsburgh, PA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://julieeckstrom.com" # the base hostname & protocol for your site
github_username:  julieeckstrom
linkedin_username: julieeckstrom
include: ["_pages"]
collections: 
 projects:
  output: true
  title: Projects

# Build settings
markdown: kramdown